# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya'  #网络抽象层
  pod 'SVProgressHUD'
  pod 'Moya/RxSwift'
  pod 'HandyJSON' #JSON转模型

end
